package online.yudream.minecraft.bridge.velocity.config;

import java.util.List;

/** The commented config written on first start. */
public final class ConfigTemplate {

    private static final List<String> LINES = List.of(
            "# YuDream Velocity bridge configuration.",
            "#",
            "# This plugin is the only component that talks to YuDream Admin. Backend servers running the",
            "# companion Fabric mod feed it player activity over the yudream:bridge plugin message",
            "# channel; the proxy itself owns player presence.",
            "",
            "enabled=true",
            "",
            "# ---------------------------------------------------------------------------",
            "# YuDream Admin endpoint",
            "# ---------------------------------------------------------------------------",
            "# Base URL of YuDream Admin. Do not include a trailing slash.",
            "api.base-url=http://127.0.0.1:8080",
            "# Server id created in the YuDream Admin minecraft-server plugin. One id covers the whole",
            "# proxy network: the reported downstream server is selected with target.server below.",
            "api.server-id=",
            "# API key with plugin:minecraft-server:report. /yudreammc status also needs",
            "# plugin:minecraft-server:manage. Never logged.",
            "api.api-key=",
            "# Adds a top-level \"serverName\" field to snapshot bodies. Leave false unless YuDream Admin",
            "# is known to ignore unknown JSON fields: a strictly validating backend rejects the body.",
            "api.include-server-name-in-snapshot=false",
            "",
            "# ---------------------------------------------------------------------------",
            "# Which downstream server is reported",
            "# ---------------------------------------------------------------------------",
            "# Name of the backend server whose player list is uploaded, as it appears in velocity.toml",
            "# (for example \"survival\"). Empty means nothing is reported until it is set, either here or",
            "# at runtime with /yudreammc target <server>.",
            "target.server=",
            "# Refuse to report anything until that backend's Fabric sensor has said hello. Keeps partial",
            "# data (presence without AFK, or a backend that silently lost the mod) out of YuDream Admin.",
            "target.require-sensor=true",
            "# Warn when a confirmed sensor has not been heard from for this long while players are on it.",
            "target.sensor-timeout-seconds=90",
            "# How often the proxy asks the target backend's sensors to re-introduce themselves.",
            "target.probe-interval-seconds=30",
            "# How far (in blocks) a player must move before the sensor counts it as activity.",
            "target.move-activity-min-blocks=1.0",
            "",
            "# ---------------------------------------------------------------------------",
            "# Reporting cadence",
            "# ---------------------------------------------------------------------------",
            "# Full online-player snapshot interval. Snapshots let YuDream Admin reconcile events that",
            "# were missed while it was unreachable.",
            "snapshot.interval-seconds=60",
            "",
            "# ---------------------------------------------------------------------------",
            "# HTTP behaviour and report logging",
            "# ---------------------------------------------------------------------------",
            "http.connect-timeout-ms=5000",
            "http.read-timeout-ms=8000",
            "http.retry-attempts=3",
            "http.retry-delay-ms=1500",
            "http.queue-capacity=1000",
            "# Journal undelivered reports so they survive a proxy restart. Delivery is at-least-once.",
            "http.persist-queue=true",
            "http.queue-file=report-queue.jsonl",
            "# Logs every event accepted into the async report queue.",
            "http.log-queued=false",
            "# Logs every HTTP attempt, including retries.",
            "http.log-attempts=false",
            "# Logs successful reports.",
            "http.log-success=true",
            "# Logs final failures after all retry attempts.",
            "http.log-failures=true",
            "# Include playerId and eventAt in report logs. The API key is never logged.",
            "http.log-payload=false",
            "",
            "# ---------------------------------------------------------------------------",
            "# AFK detection",
            "# ---------------------------------------------------------------------------",
            "# Activity signals come from the backend Fabric sensor, because a proxy cannot see chat or",
            "# movement. Presence always comes from the proxy.",
            "afk.enabled=true",
            "afk.timeout-seconds=300",
            "afk.check-interval-seconds=30",
            "",
            "# ---------------------------------------------------------------------------",
            "# Startup, shutdown and reserved events",
            "# ---------------------------------------------------------------------------",
            "# After /yudreammc reload, re-report players already on the target backend.",
            "startup.sync-online-on-enable=true",
            "# Keep false for normal proxy restarts. Enable only if you want forced quit reports.",
            "shutdown.report-quit-on-disable=false",
            "shutdown.flush-timeout-ms=5000",
            "# Cross-server switch events. Reserved: YuDream Admin must accept the server/switch path and",
            "# the fromServer/toServer fields before this can be enabled. Off by default.",
            "events.server-switch=false",
            "",
            "# ---------------------------------------------------------------------------",
            "# /yudreammc permissions",
            "# ---------------------------------------------------------------------------",
            "# The console can always run the command. A player needs the permission node below (granted",
            "# by LuckPerms and friends) or to be listed in command.admins.",
            "command.permission=yudreammc.admin",
            "# Comma separated player names or UUIDs allowed to run /yudreammc.",
            "command.admins=",
            "",
            "# Account names refused before Velocity asks the authentication server about them.",
            "# Velocity authenticates first and only then fires LoginEvent, so a client stuck in a",
            "# reconnect loop costs one Yggdrasil call per attempt. Left unchecked that burns the API's",
            "# per-IP rate limit and real players start seeing \"too many login attempts\".",
            "login.blocked-names="
    );

    private ConfigTemplate() {
    }

    public static String render() {
        StringBuilder out = new StringBuilder();
        for (String line : LINES) {
            out.append(line).append(System.lineSeparator());
        }
        return out.toString();
    }
}
