package online.yudream.minecraft.bridge.velocity.config;

import java.util.List;

/** The commented config written on first start. */
public final class ConfigTemplate {

    private static final List<String> LINES = List.of(
            "# YuDream Velocity bridge configuration.",
            "#",
            "# This plugin is the only component that talks to YuDream Admin. Backend servers running the",
            "# companion Fabric mod feed it player activity over the yudream:bridge plugin message",
            "# channel; the proxy itself owns player presence.",
            "",
            "enabled=true",
            "",
            "# ---------------------------------------------------------------------------",
            "# YuDream Admin endpoint",
            "# ---------------------------------------------------------------------------",
            "# Base URL of YuDream Admin. Do not include a trailing slash.",
            "api.base-url=http://127.0.0.1:8080",
            "# Server id created in the YuDream Admin minecraft-server plugin. One id covers the whole",
            "# proxy network: every downstream server below is reported to it and stored separately.",
            "api.server-id=",
            "# API key with plugin:minecraft-server:report. /yudreammc status also needs",
            "# plugin:minecraft-server:manage. Never logged.",
            "api.api-key=",
            "# Adds a top-level \"serverName\" field to the legacy flat snapshot body. Unused by this",
            "# proxy (it sends the grouped form) but kept for the flat shape. Leave false unless",
            "# YuDream Admin is known to ignore unknown JSON fields.",
            "api.include-server-name-in-snapshot=false",
            "",
            "# ---------------------------------------------------------------------------",
            "# Downstream servers and the sensor gate",
            "# ---------------------------------------------------------------------------",
            "# EVERY downstream server Velocity knows about is reported, each as its own sub-server, so",
            "# a player moving fabric -> paper is a quit on fabric plus a join on paper and YuDream Admin",
            "# keeps the two durations side by side. There is no switch for this.",
            "target.server=",
            "# target.server is only the default / login-entry marker: the backend new players land on.",
            "# /yudreammc target reads and writes it. It does NOT select, enable or suppress reporting.",
            "# Refuse to report a sub-server until ITS OWN Fabric sensor has said hello. Applied per",
            "# sub-server: a backend without the mod is skipped while every other backend keeps",
            "# reporting, and a listed sub-server with an empty roster still reconciles departures.",
            "target.require-sensor=true",
            "# Warn when a confirmed sensor has not been heard from for this long while players are on it.",
            "target.sensor-timeout-seconds=90",
            "# How often the proxy asks every backend's sensors to re-introduce themselves.",
            "target.probe-interval-seconds=30",
            "# How far (in blocks) a player must move before the sensor counts it as activity.",
            "target.move-activity-min-blocks=1.0",
            "",
            "# ---------------------------------------------------------------------------",
            "# Reporting cadence",
            "# ---------------------------------------------------------------------------",
            "# Snapshot interval. Each snapshot carries one roster per sub-server, which is how YuDream",
            "# Admin reconciles events missed while it was unreachable without mixing sub-servers up.",
            "snapshot.interval-seconds=60",
            "",
            "# ---------------------------------------------------------------------------",
            "# Group topology (一键解析群组服)",
            "# ---------------------------------------------------------------------------",
            "# Report this proxy's downstream-server list to YuDream Admin, so the group server shows its",
            "# sub-servers there. A proxy's Server List Ping never exposes its backends, so the bridge is",
            "# the only component that can tell Admin what the network contains.",
            "topology.enabled=true",
            "# How often the list is reported. Reported once shortly after startup as well.",
            "topology.interval-seconds=60",
            "# The address(es) players connect to for THIS proxy, comma separated. Admin matches a report",
            "# against the server entries' line addresses, which is what lets you resolve a group server",
            "# without copying an Admin server id into this file. Velocity only exposes its bind address,",
            "# which is normally 0.0.0.0, so set this to the real hostname: e.g. play.example.com",
            "topology.addresses=",
            "",
            "# ---------------------------------------------------------------------------",
            "# HTTP behaviour and report logging",
            "# ---------------------------------------------------------------------------",
            "http.connect-timeout-ms=5000",
            "http.read-timeout-ms=8000",
            "http.retry-attempts=3",
            "http.retry-delay-ms=1500",
            "http.queue-capacity=1000",
            "# Journal undelivered reports so they survive a proxy restart. Delivery is at-least-once.",
            "http.persist-queue=true",
            "http.queue-file=report-queue.jsonl",
            "# Logs every event accepted into the async report queue.",
            "http.log-queued=false",
            "# Logs every HTTP attempt, including retries.",
            "http.log-attempts=false",
            "# Logs successful reports.",
            "http.log-success=true",
            "# Logs final failures after all retry attempts.",
            "http.log-failures=true",
            "# Include playerId and eventAt in report logs. The API key is never logged.",
            "http.log-payload=false",
            "",
            "# ---------------------------------------------------------------------------",
            "# AFK detection",
            "# ---------------------------------------------------------------------------",
            "# Activity signals come from the backend Fabric sensor, because a proxy cannot see chat or",
            "# movement. Presence always comes from the proxy.",
            "afk.enabled=true",
            "afk.timeout-seconds=300",
            "afk.check-interval-seconds=30",
            "",
            "# ---------------------------------------------------------------------------",
            "# Startup, shutdown and reserved events",
            "# ---------------------------------------------------------------------------",
            "# After /yudreammc reload, re-report players already on the target backend.",
            "startup.sync-online-on-enable=true",
            "# Keep false for normal proxy restarts. Enable only if you want forced quit reports.",
            "shutdown.report-quit-on-disable=false",
            "shutdown.flush-timeout-ms=5000",
            "# Cross-server switch events. Reserved: YuDream Admin must accept the server/switch path and",
            "# the fromServer/toServer fields before this can be enabled. Off by default.",
            "events.server-switch=false",
            "",
            "# ---------------------------------------------------------------------------",
            "# /yudreammc permissions",
            "# ---------------------------------------------------------------------------",
            "# The console can always run the command. A player needs the permission node below (granted",
            "# by LuckPerms and friends) or to be listed in command.admins.",
            "command.permission=yudreammc.admin",
            "# Comma separated player names or UUIDs allowed to run /yudreammc.",
            "command.admins=",
            "",
            "# Account names refused before Velocity asks the authentication server about them.",
            "# Velocity authenticates first and only then fires LoginEvent, so a client stuck in a",
            "# reconnect loop costs one Yggdrasil call per attempt. Left unchecked that burns the API's",
            "# per-IP rate limit and real players start seeing \"too many login attempts\".",
            "login.blocked-names="
    );

    private ConfigTemplate() {
    }

    public static String render() {
        StringBuilder out = new StringBuilder();
        for (String line : LINES) {
            out.append(line).append(System.lineSeparator());
        }
        return out.toString();
    }
}
